package com.medieval.keyboard

object MedievalFallbackMap {

    val map: HashMap<String, String> = hashMapOf(
        // === COMMON SUBSTITUTIONS ===
        "yes" to "aye",
        "yeah" to "aye, verily",
        "yep" to "aye",
        "no" to "nay",
        "nope" to "nay, I shalt not",
        "you" to "thou",
        "your" to "thy",
        "yours" to "thine",
        "hello" to "hail",
        "hi" to "well met",
        "hey" to "hark",
        "goodbye" to "fare thee well",
        "bye" to "Godspeed",
        "please" to "prithee",
        "sorry" to "I cry thee mercy",
        "thanks" to "thou hast my gratitude",
        "friend" to "comrade",
        "enemy" to "knave",
        "stupid" to "addlepated",
        "ugly" to "misbegotten",
        "drunk" to "in one's cups",
        "crazy" to "moon-mad",
        "money" to "coin",
        "food" to "victuals",
        "eat" to "sup",
        "walk" to "venture forth",
        "run" to "make great haste",
        "house" to "dwelling",
        "home" to "hearth and dwelling",
        "clothes" to "garments",
        "phone" to "enchanted scrying glass",
        "internet" to "the great arcane network",
        "car" to "iron carriage",
        "computer" to "thinking engine",
        "police" to "the constabulary",
        "doctor" to "apothecary",
        "work" to "toil",
        "job" to "toil",
        "boss" to "liege",
        "cool" to "most gallant",
        "bad" to "most foul",
        "awesome" to "most magnificent",
        "annoying" to "vexing",
        "fight" to "skirmish",
        "kill" to "smite",
        "love" to "adore",
        "hate" to "despise",
        "good" to "most worthy",
        "great" to "most splendid",

        // === ORIGINAL SLANG ===
        "lol" to "I doth laugh heartily",
        "omg" to "by all the saints",
        "wtf" to "what devilry is this",
        "ok" to "aye, so be it",
        "okay" to "aye, so be it",
        "bro" to "good fellow and brother in arms",
        "dude" to "good sir",
        "girl" to "maiden",
        "guy" to "fellow",
        "sick" to "most gallant",
        "fire" to "of great magnificence",
        "lit" to "most resplendent",
        "bruh" to "good fellow",
        "fam" to "mine blood and kin",
        "goat" to "the greatest champion this kingdom hath ever witnessed",
        "shade" to "veiled insult most cunning",
        "tea" to "gossip most tantalizing",

        // === GREETINGS & CASUAL CHAT ===
        "wassup" to "hark, what tidings dost thou bring?",
        "wazzup" to "hark, what tidings dost thou bring?",
        "sup" to "hark, what tidings dost thou bring?",
        "wyd" to "what manner of toil dost thou undertake at this hour?",
        "hmu" to "send a raven unto me",
        "brb" to "I shall return hence, tarry a moment",
        "gtg" to "I must away with great haste",
        "ttyl" to "we shall speak anon",
        "ngl" to "I shall not deceive thee",
        "tbh" to "in honest truth, I confess",
        "imo" to "methinks",
        "imho" to "in my most humble opinion, good sir",
        "smh" to "I shaketh mine head in great despair",
        "lmao" to "I am deceased with laughter, forsooth",
        "rofl" to "I doth roll upon the ground in great hysterics",
        "gg" to "well fought, thou gallant warrior",
        "wp" to "most valiant effort, good knight",

        // === GEN Z SLANG ===
        "cap" to "thou speakest falsehoods, knave",
        "slay" to "thou dost smite all before thee",
        "ate" to "thou didst feast upon that challenge most gloriously",
        "periodt" to "and so it is decreed, henceforth",
        "bussin" to "forsooth, 'tis a most glorious feast",
        "mid" to "most mediocre, hardly worth a farthing",
        "based" to "of most noble conviction",
        "cringe" to "most embarrassing, I cry thee mercy",
        "ratio" to "thou hast been bested in the court of public opinion",
        "bet" to "upon my honour, so be it",
        "deadass" to "in utmost sincerity, I swear upon mine soul",
        "facts" to "thou speakest true, verily",
        "lowkey" to "in secret, lest the king's men hear",
        "highkey" to "I shout it from the highest rampart",
        "vibe" to "the humour of the moment",
        "vibing" to "dwelling in pleasant and harmonious humour",
        "sus" to "most suspicious, I dare say",
        "extra" to "most theatrical beyond all reason",
        "basic" to "plain as a peasant's gruel",
        "woke" to "most enlightened beyond thine station",
        "clout" to "renown and influence within the royal court",
        "shook" to "rattled to mine very bones",

        // === HYPE & REACTION ===
        "savage" to "most ruthless and without mercy",
        "salty" to "most bitter, like the sea itself",
        "flex" to "a most ostentatious display of one's riches",
        "drip" to "most resplendent raiment",
        "fit" to "a most fine set of garments",
        "slaps" to "doth strike mine ears most pleasurably",
        "banger" to "a most rousing ballad for the ages",
        "dead" to "I am slain by this jestry",

        // === DATING & SOCIAL ===
        "ghost" to "vanish like a specter",
        "ghosted" to "vanished like a wraith in the night without word",
        "situationship" to "a courtship of most uncertain and undefined honour",
        "rizz" to "the art of courtly charm",
        "simp" to "a lovesick fool pining most pitifully",
        "stan" to "a most devoted admirer, bordering on madness",
        "ship" to "I dost pray these two souls be betrothed",
        "otp" to "my most fervently wished betrothal",
        "fomo" to "the fear of missing the great feast",
        "yolo" to "thou only walketh this earth once, seize the day",

        // === PERSONA ===
        "sigma" to "a lone wolf of most noble bearing",
        "alpha" to "the chief lord of the pack",
        "beta" to "a most craven follower",
        "npc" to "a mere peasant of no consequence",

        // === MULTI-WORD PHRASES ===
        "fr fr" to "verily, upon my honour, 'tis so",
        "no cap" to "I speak no falsehood, upon my troth",
        "no way" to "by God's wounds, thou jest surely",
        "say less" to "speak no further, I heed thee",
        "no rizz" to "possessing not a shred of courtly grace",
        "rent free" to "haunting thy thoughts like a restless wraith",
        "main character" to "the hero around whom the entire tale revolves",
        "glow up" to "a most wondrous transformation, like a phoenix reborn",
        "caught in 4k" to "witnessed by the royal portraitist in full and damning detail",
        "touch grass" to "venture beyond thy stone walls into the natural realm",
        "i'm weak" to "thou hast robbed me of all strength through laughter",
        "lowkey crying" to "mine eyes doth leak most quietly",
        "it's giving" to "it doth exude the essence of",
        "that's wild" to "most extraordinary, by the saints",
        "this ain't it" to "nay, this is most foul and unworthy",
        "it's not giving" to "it doth fail to exude any worthy essence",
        "hits different" to "doth strike the soul in a manner most peculiar",
        "hit different at 3am" to "doth weigh upon the soul most heavily in the dead of night",
        "understood the assignment" to "hath heeded the royal decree with excellence",
        "periodt no cap" to "so it is written, so it shall be done",
        "we don't do that here" to "such conduct is most unwelcome in this kingdom",
        "ate and left no crumbs" to "feasted gloriously and left naught for the ravens",
        "understood" to "thy words hath reached mine ears, so be it",
        "L" to "a most grievous defeat, thou wretch",
        "W" to "a most glorious victory, well met",

        // === MORE COMMON WORDS ===
        "man" to "fellow",
        "woman" to "lady",
        "wife" to "beloved wife",
        "husband" to "lord husband",
        "king" to "sovereign",
        "queen" to "sovereign lady",
        "city" to "great city",
        "town" to "hamlet",
        "village" to "hamlet",
        "water" to "water",
        "beer" to "ale",
        "wine" to "mead",
        "sword" to "blade",
        "horse" to "steed",
        "dog" to "hound",
        "cat" to "mouser",
        "night" to "eve",
        "day" to "morrow",
        "morning" to "morrow's dawn",
        "evening" to "vespers",
        "week" to "sennight",
        "today" to "this very day",
        "tomorrow" to "on the morrow",
        "yesterday" to "yester-eve",
        "want" to "desire",
        "need" to "require most urgently",
        "have" to "possess",
        "go" to "venture forth",
        "come" to "approach",
        "see" to "behold",
        "look" to "gaze upon",
        "think" to "methinks",
        "know" to "doth know",
        "say" to "proclaim",
        "tell" to "declare",
        "give" to "bestow",
        "take" to "seize",
        "make" to "forge",
        "get" to "procure",
        "try" to "endeavor",
        "help" to "lend thine aid",
        "stop" to "halt",
        "wait" to "tarry",
        "fast" to "swift",
        "slow" to "leisurely",
        "big" to "great",
        "small" to "wee",
        "old" to "ancient",
        "new" to "freshly wrought",
        "happy" to "merry",
        "sad" to "woeful",
        "angry" to "wrathful",
        "scared" to "afeared",
        "tired" to "weary",
        "hungry" to "famished",
        "rich" to "wealthy",
        "poor" to "destitute",
        "strong" to "stalwart",
        "weak" to "feeble",
        "smart" to "learned",
        "brave" to "valiant",
        "afraid" to "craven",
        "alive" to "among the living",
        "war" to "great conflict",
        "peace" to "tranquility",
        "truth" to "verity",
        "lie" to "falsehood",
        "God" to "the Almighty",
        "devil" to "the fiend",
        "church" to "the chapel",
        "school" to "academy of learning",
        "book" to "tome",
        "letter" to "missive",
        "message" to "dispatch",
        "text" to "scroll",
        "email" to "enchanted missive",
        "password" to "secret incantation",
        "wifi" to "ethereal connection",
        "battery" to "arcane reserves",
        "selfie" to "self-portrait most vain",
        "photo" to "portrait",
        "video" to "moving portrait",
        "movie" to "grand theatrical spectacle",
        "music" to "minstrel's art",
        "song" to "ballad",
        "dance" to "revelry",
        "party" to "grand feast",
        "date" to "courtship",
        "relationship" to "courtship most serious",
        "breakup" to "severing of bonds",
        "boring" to "tedious",
        "exciting" to "thrilling",
        "beautiful" to "most fair",
        "handsome" to "comely",
        "thank" to "give thanks",
        "children" to "younglings",
        "baby" to "babe",
        "sleep" to "slumber",
        "wake" to "rouse",
        "laugh" to "cackle with mirth",
        "cry" to "weep",
        "smile" to "grin most warmly",
        "yell" to "bellow",
        "whisper" to "murmur",
        "speak" to "utter",
        "quiet" to "hush",
        "loud" to "thunderous",
        "dark" to "shrouded in shadow",
        "light" to "illuminated",
        "hot" to "scorching",
        "cold" to "possessing an air of effortless magnificence",
        "rain" to "heavens weep",
        "sun" to "celestial orb",
        "moon" to "pale moon",
        "star" to "heavenly body",
        "road" to "path",
        "street" to "thoroughfare",
        "door" to "portal",
        "window" to "casement",
        "bed" to "bedchamber",
        "table" to "board",
        "chair" to "seat",
        "store" to "merchant's shop",
        "buy" to "purchase",
        "sell" to "peddle",
        "pay" to "render payment",
        "free" to "without cost",
        "expensive" to "most costly",
        "cheap" to "of little worth",

        // === STREET & FRIEND SLANG ===
        "huzz" to "thou most disreputable wench of questionable virtue",
        "huz" to "thou most disreputable wench of questionable virtue",
        "bruzz" to "mine most trusted brother in arms",
        "bruz" to "mine most trusted brother in arms",
        "cuzz" to "mine kinsman of the realm",
        "cuz" to "mine kinsman of the realm",
        "gang" to "mine most loyal band of knights",
        "homie" to "mine sworn companion of the parish",
        "dawg" to "thou faithful hound, mine dearest ally",
        "sis" to "good maiden and sister of mine heart",
        "bestie" to "mine most cherished companion in this mortal realm",
        "twin" to "mine soul's mirror, we art one",
        "plug" to "mine most clandestine merchant of wares",
        "opps" to "mine sworn enemies and rival clan",
        "ops" to "mine sworn enemies and rival clan",
        "opp" to "a foe most treacherous from a rival house",
        "beef" to "a most bitter quarrel and blood feud",
        "fake" to "a most duplicitous and two-faced wretch",
        "snake" to "a viper most treacherous hiding in friendly garb",
        "rat" to "an informant most vile, a spy for the crown",
        "snitch" to "one who doth whisper secrets unto the king's men",
        "real" to "of the truest and most genuine nature",
        "unreal" to "so magnificent it straineth belief",
        "surreal" to "as strange as a dream sent by the faeries",

        // === STREET & FRIEND PHRASES ===
        "ride or die" to "sworn to stand by mine side til the final battle",
        "day one" to "loyal since the very first cockcrow",
        "squash the beef" to "let us broker peace and end this blood feud",
        "on sight" to "I shall smite thee the moment thine wretched face appears",
        "move different" to "thou dost carry thyself unlike common peasantry",
        "built different" to "forged of sterner stuff than ordinary men",
        "no printer" to "mine word is mine bond, no royal decree needed",
        "real one" to "a soul of most genuine and noble character",
        "clout chaser" to "a glory hound seeking unearned renown",
        "pick me" to "one who doth grovel most pitifully for approval",

        // === HYPE & REACTION SLANG ===
        "cooked" to "in most dire straits with no escape",
        "pressed" to "most vexed and wound up like a siege engine",
        "ick" to "a most revolting sensation hath overcome me",
        "obsessed" to "bewitched and consumed most entirely",
        "delulu" to "lost in delusions most fantastical and unfounded",
        "era" to "mine current chapter of this great tale",
        "fresh" to "most pristine and splendid in appearance",
        "hard" to "of the most uncompromising and impressive quality",
        "goated" to "elevated to legendary status beyond all others",
        "overrated" to "praised far beyond its meagre deserving",
        "underrated" to "deserving far greater renown than granted",
        "sleeper" to "a hidden gem known only to the most discerning",
        "trash" to "absolute refuse not worth a single farthing",
        "cope" to "find thyself some manner of comfort in defeat",
        "seethe" to "boil with rage most impotent and unbecoming",
        "mald" to "lose both thy composure and thy hair simultaneously",
        "swear" to "I doth swear upon mine honour",
        "lying" to "thou speakest nothing but falsehoods, thou deceiver",
        "relax" to "ease thy troubled mind, good sir",
        "chill" to "be of calm and pleasant humour",
        "hits" to "doth strike the palate most pleasurably",

        // === HYPE & REACTION PHRASES ===
        "go crazy" to "descend into most glorious madness",
        "go off" to "unleash thy fury, hold nothing back",
        "go off sis" to "speak thy truth maiden, let the whole kingdom hear",
        "not me" to "prithee do not look upon me for such folly",
        "the way i" to "forsooth, observe how I doth",
        "i can't" to "mine strength doth fail me entirely",
        "i'm dead" to "thou hast slain me where I stood",
        "send help" to "dispatch thy swiftest raven, I am in dire peril",
        "it's over" to "the battle is lost, all hope hath fled",
        "we're so back" to "the army doth rise again, victory is nigh",
        "he's cooked" to "that poor wretch is well and truly done for",
        "bro is cooked" to "yonder fool hath sealed his own fate",
        "stick a fork in me" to "I am as done as a feast day pig upon the spit",
        "not the" to "by the saints, anything but the",
        "the audacity" to "the sheer brazen impudence of this knave",
        "mad pressed" to "consumed by fury most unbecoming of thy station",
        "calm down" to "still thy tempestuous spirit, I prithee",
        "no chill" to "possessing not a single moment of peaceful temper",
        "got the ick" to "mine heart hath recoiled in disgust most profound",
        "caught feelings" to "mine heart hath been most inconveniently ensnared",
        "down bad" to "reduced to the most pitiful and lovesick state",
        "down horrendous" to "in a state of wretchedness beyond all description",
        "parasocial" to "devoted to one who knoweth not of thine existence",
        "delulu is the solulu" to "only through magnificent delusion doth one prevail",
        "touch starved" to "denied human warmth like a hermit in a cold tower",
        "in my villain era" to "I hath embraced mine darker nature most gleefully",
        "in my flop era" to "currently dwelling in a most unproductive chapter",
        "in my healing era" to "mending mine wounds like a knight after great battle",
        "in my glow up era" to "transforming like a dragon shedding its old scales",
        "roman empire" to "that which occupies mine thoughts unbidden and often",
        "he doesn't know" to "the poor fool remaineth blissfully unaware",
        "understood the vibe" to "hath read the room with most admirable perception",
        "didn't pass the vibe check" to "hath failed the test of pleasant humour most miserably",

        // === ARGUMENT & CLAP BACK ===
        "you're cooked" to "thou art finished, prepare thy affairs",
        "ratio'd" to "bested in the court of public opinion, thou wretched fool",
        "i said what i said" to "mine words stand firm as castle walls",
        "keep my name out your mouth" to "speak not mine name with thy wretched tongue",
        "say that to my face" to "speak those words whilst facing mine blade, coward",
        "on god" to "I swear upon all that is holy and sacred",
        "not lying" to "every word from mine lips is pure truth",
        "nah bro" to "nay good sir, I shalt not accept this",
        "bro really said" to "the audacity of this knave who proclaimed",
        "bro thought" to "this fool genuinely believed in his addled mind",
        "tell me why" to "prithee explain to me the reasoning behind this madness",
        "for what" to "for what earthly reason, I demand to know",
        "at what cost" to "but at what terrible price was this victory won",
        "this you?" to "art thou truly responsible for this shameful act?",
        "caught lacking" to "discovered in a most vulnerable and unguarded state",
        "stay mad" to "wallow in thy bitterness, it matters not to me",
        "cry about it" to "weep thy tears into the river, I care not",
        "touch some grass" to "remove thyself from thy stone tower and breathe fresh air",
        "log off" to "close thy enchanted scrying glass and venture outside",
        "get a life" to "acquire purpose beyond this screen, thou hollow vessel",
        "get good" to "hone thy skills or be forever bested, thou novice",
        "skill issue" to "a deficiency of ability most fundamental",
        "cope and seethe" to "wallow in denial and simmer in thine own fury",
        "touch grass and mald" to "venture outside and rage at the very sky",

        // === FOOD & DAILY LIFE PHRASES ===
        "no cap bussin" to "upon my honour this feast is of divine quality",
        "it's giving slay" to "it doth radiate excellence most magnificent",
        "slaps hard" to "assaults mine senses with magnificent force",
        "fire ngl" to "most magnificent, I shall not deceive thee",
        "mid af" to "most thoroughly mediocre in every conceivable way",
        "certified banger" to "decreed by royal proclamation to be a masterwork",
        "goated with the sauce" to "a legend draped in the most mysterious and potent gifts",
        "the sauce" to "the mysterious secret ingredient of greatness",
        "dripped out" to "adorned in the most magnificent raiment imaginable",
        "clean fit" to "garments of the most impeccable and noble quality",

        // === TIKTOK & CONTENT CREATOR SLANG ===
        "fyp" to "may this reach the royal proclamation board",
        "for you page" to "the royal herald's board of curated announcements",
        "algorithm" to "the dark enchantment that controls what the masses see",
        "blew up" to "went forth and conquered all of the realm's attention",
        "went viral" to "spread through the kingdom like the sweating sickness",
        "content" to "thy creative proclamations and artistic offerings",
        "creator" to "a craftsman of tales and proclamations",
        "collab" to "a joint quest undertaken by two noble creators",
        "drop" to "release thy wares upon the awaiting masses",
        "merch" to "garments and trinkets bearing thy house sigil",
        "stream" to "perform thy arts live before a gathered crowd",
        "clip" to "a captured moment preserved by the royal scribe",
        "highlight reel" to "a collection of thine greatest victories",
        "flop" to "a most catastrophic failure before the entire court",
        "cancelled" to "banished from the kingdom by public decree",
        "cancelld" to "banished from the kingdom by public decree",
        "cancel culture" to "the mob's swift justice and banishment decrees",
        "influencer" to "one who shapeth the opinions of the common folk",
        "hot take" to "a most controversial proclamation sure to stir the court",
        "unpopular opinion" to "a view most unwelcome in polite company",
        "thread" to "a lengthy scroll of connected proclamations",
        "ratio this" to "attempt to best this proclamation, I dare thee",
        "comment section" to "the town square of heated discourse",
        "live" to "performing before the court at this very moment",

        // === GAMING SLANG ===
        "gg ez" to "a most effortless victory, hardly worth celebrating",
        "noob" to "a most inexperienced and bumbling novice knight",
        "tryhard" to "one who doth strain every sinew in desperate pursuit of glory",
        "sweaty" to "exerting thine self most unbecomingly",
        "grinding" to "toiling endlessly in pursuit of greater power",
        "loot" to "the spoils of battle most gloriously seized",
        "nerf" to "to weaken a once mighty champion by royal decree",
        "buff" to "to empower a warrior by the grace of the game gods",
        "meta" to "the dominant strategy favoured by the learned tacticians",
        "op" to "overpowered beyond all reasonable measure",
        "broken" to "so powerful it doth shatter the natural order",
        "clutch" to "snatching victory from the jaws of certain defeat",
        "carry" to "bearing thine entire team upon thine back like Atlas",
        "int" to "to throw the battle most deliberately and shamefully",
        "throw" to "to squander victory through thine own incompetence",
        "bot" to "a hollow automaton devoid of genuine skill",
        "afk" to "absent from the battlefield without leave",
        "respawn" to "return from death's embrace for another attempt",
        "final boss" to "the ultimate adversary standing between thee and glory",
        "side quest" to "a minor errand most distracting from the main quest",
        "npc behavior" to "acting as a mindless background peasant",
        "main character energy" to "conducting thyself as the hero of the grand tale",
        "speedrun" to "to complete a quest with unnatural and reckless haste",
        "rage quit" to "to flee the battlefield in furious disgrace",

        // === RELATIONSHIP & DATING SLANG ===
        "talking stage" to "the delicate period of courtly correspondence",
        "official" to "formally betrothed before witnesses",
        "it's complicated" to "our courtship is mired in confusion most profound",
        "the ick" to "a sudden and profound revulsion for one's suitor",
        "red flag" to "a warning sign most ominous flying above the castle",
        "green flag" to "a most auspicious sign of good character",
        "toxic" to "poisonous to thine soul and wellbeing",
        "gaslighting" to "making one question their own sanity through dark sorcery",
        "love bombing" to "overwhelming with affection like a siege of the heart",
        "breadcrumbing" to "leading one on with mere crumbs of false hope",
        "ghosting" to "vanishing like a wraith without so much as a farewell",
        "slow burn" to "a romance kindling slowly like embers in the hearth",
        "enemies to lovers" to "from sworn adversaries to besotted companions",
        "he's not giving" to "that suitor doth fail to provide what was promised",
        "she's different" to "this maiden possesseth qualities most extraordinary",
        "they're obsessed with me" to "I hath bewitched them entirely it seems",
        "manifesting" to "willing something into existence through sheer conviction",
        "soft launch" to "presenting thy companion to the court most cautiously",
        "hard launch" to "presenting thy companion before the entire kingdom at once",
        "we broke up" to "our courtship hath come to a most sorrowful end",
        "it's giving ex" to "this doth remind me of mine most wretched former suitor",
        "main character moment" to "a pivotal scene in thine own great romantic tale",

        // === MENTAL HEALTH & MOOD SLANG ===
        "not okay" to "mine spirit doth suffer most grievously",
        "in my feels" to "overcome by emotions most turbulent and powerful",
        "emotional damage" to "wounded in mine very soul",
        "it do be like that" to "verily, such is the nature of this cruel world",
        "that's rough buddy" to "a most grievous circumstance, thou hast mine sympathies",
        "big oof" to "a wound to the pride most substantial",
        "oof" to "a blow to mine very being",
        "mood" to "a state of being that resonateth with mine own soul",
        "big mood" to "a sentiment that speaketh to mine soul most profoundly",
        "same" to "verily, mine own experience doth mirror this exactly",
        "felt that" to "those words didst pierce mine heart most directly",
        "living rent free" to "haunting mine thoughts without paying tribute",
        "brain rot" to "mine mind hath been corrupted by excessive foolery",
        "rotting" to "wasting away upon mine bed chamber floor",
        "rest" to "seeking repose most desperately",
        "burnout" to "mine fire hath been extinguished through overwork",
        "adulting" to "attempting the impossible tasks of responsible lordship",
        "i can't adult today" to "I refuse mine lordly duties on this particular morrow",
        "executive dysfunction" to "unable to commence even the simplest of quests",
        "hyperfixation" to "consumed entirely by a single obsession like a cursed knight",
        "intrusive thoughts" to "dark whispers from the devils of mine own mind",
        "therapy arc" to "embarking upon a quest of inner healing and self-knowledge",
        "healing" to "mending mine wounds most diligently",
        "glowing" to "radiating an inner light most wondrous",
        "thriving" to "flourishing like a kingdom in its golden age",
        "surviving" to "merely clinging to life by mine fingertips",

        // === MISCELLANEOUS MODERN SLANG ===
        "the math ain't mathing" to "the numbers doth not add up by any arcane calculation",
        "ok boomer" to "aye, whatever thou sayest, thou ancient and outdated elder",
        "respectfully" to "with all due courtesy and diplomatic restraint",
        "respectfully no" to "with the utmost respect I must firmly decline",
        "with all due respect" to "with humble genuflection before thy station",
        "that's not giving" to "this doth fail to provide what was promised",
        "the bar is low" to "the standard of excellence hath been set most meagrely",
        "the bar was low and he still tripped" to "the standard was a puddle yet still he drowned",
        "down tremendously" to "fallen to the most catastrophic depths imaginable",
        "we go again" to "once more unto the breach, dear friends",
        "here we go" to "brace thyself, for it doth begin anew",
        "i'm so done" to "mine patience hath been utterly and completely exhausted",
        "i give up" to "I yield, I lay down mine sword entirely",
        "why though" to "but for what conceivable reason, I implore thee",
        "how" to "by what dark sorcery hath this come to pass",
        "why is this so hard" to "why doth fate make this simple quest so treacherous",
        "we don't deserve dogs" to "we are unworthy of these loyal and noble creatures",
        "dog tax" to "thou owest the court a portrait of thine loyal hound",
        "pet tax" to "thou owest the court a portrait of thine beloved creature",
        "timestamp" to "the exact moment recorded in the royal chronicles",
        "source?" to "produce thine evidence before the royal court, I demand it",
        "citation needed" to "the royal scholars require proof of this bold claim",
        "based and redpilled" to "enlightened and freed from the shackles of false belief",
        "chronically online" to "permanently enslaved to thine enchanted scrying glass",
        "grass toucher" to "one who hath ventured outside and returned most refreshed",
        "it's giving very much" to "it doth radiate this essence with great abundance",
        "no thoughts head empty" to "mine mind is as bare as a monk's tonsure",
        "vibe check passed" to "thou hast been deemed of pleasant and worthy humour",
        "vibe check failed" to "thou hast been found lacking in basic pleasant qualities",
        "understood the assignment and ate" to "not only heeded the quest but conquered it gloriously",
        "mother" to "the supreme and most venerated ruler of all",
        "father" to "the patriarch most revered and powerful",
        "she's mother" to "she doth reign supreme above all others",
        "that's so real" to "verily this speaketh a profound and undeniable truth",
        "i feel seen" to "mine soul hath been witnessed and understood at last",
        "core memory" to "a moment etched into mine very soul for all eternity",
        "character development" to "the growth of one's noble qualities through hardship",
        "plot twist" to "a most unexpected turn in this great tale",
        "villain arc" to "descending into darkness and abandoning one's noble path",
        "redemption arc" to "returning from darkness to reclaim one's honour",
        "lore" to "the deep and ancient history of a person or realm",
        "lore drop" to "a sudden revelation of most ancient and significant history",
        "deep lore" to "secrets buried so deep only scholars dare uncover them",
        "this is lore" to "this shall be recorded in the chronicles of the realm",

        // === COMMON VERBS ===
        "going" to "venturing forth",
        "went" to "did venture forth",
        "gone" to "departed hence",
        "coming" to "arriving hence",
        "came" to "didst arrive",
        "seeing" to "beholding",
        "saw" to "did behold",
        "seen" to "beheld",
        "thinking" to "pondering",
        "thought" to "didst ponder",
        "knowing" to "being well versed",
        "knew" to "didst know",
        "wanting" to "desiring greatly",
        "wanted" to "didst desire",
        "getting" to "procuring",
        "got" to "didst procure",
        "making" to "fashioning",
        "made" to "didst fashion",
        "taking" to "seizing upon",
        "took" to "didst seize",
        "giving" to "bestowing",
        "gave" to "didst bestow",
        "telling" to "declaring unto",
        "told" to "didst declare",
        "saying" to "proclaiming",
        "said" to "didst proclaim",
        "helping" to "lending aid",
        "helped" to "didst render aid",
        "trying" to "endeavouring",
        "tried" to "didst endeavour",
        "ask" to "beseech",
        "asking" to "beseeching",
        "asked" to "didst beseech",
        "show" to "reveal unto",
        "showing" to "revealing",
        "showed" to "didst reveal",
        "move" to "make way",
        "moving" to "making way",
        "moved" to "didst make way",
        "living" to "dwelling",
        "lived" to "didst dwell",
        "believe" to "holdeth faith",
        "bring" to "deliver unto",
        "bringing" to "delivering",
        "brought" to "didst deliver",
        "write" to "scribe",
        "writing" to "scribing",
        "wrote" to "didst scribe",
        "sit" to "take thy seat",
        "sitting" to "seated upon",
        "stand" to "rise to thy feet",
        "standing" to "standing firm",
        "stood" to "didst stand firm",
        "hold" to "grasp firmly",
        "holding" to "grasping",
        "held" to "didst grasp",
        "learn" to "gain knowledge",
        "learning" to "gaining wisdom",
        "learned" to "didst gain knowledge",
        "grow" to "flourish",
        "growing" to "flourishing",
        "grew" to "didst flourish",
        "open" to "unseal",
        "close" to "seal shut",
        "start" to "commence",
        "feel" to "doth sense",
        "feeling" to "sensing",
        "felt" to "didst sense",
        "leave" to "depart from",
        "leaving" to "departing",
        "left" to "didst depart",
        "call" to "summon",
        "calling" to "summoning",
        "called" to "didst summon",
        "read" to "peruse",
        "reading" to "perusing",
        "meet" to "make acquaintance of",
        "meeting" to "an audience with",
        "met" to "didst encounter",
        "change" to "transform",
        "follow" to "accompany",
        "speaking" to "uttering",
        "spoke" to "didst utter",
        "find" to "discover",
        "finding" to "discovering",
        "found" to "didst discover",
        "hear" to "hearken",
        "hearing" to "hearkening",
        "heard" to "didst hearken",
        "sing" to "regale with song",
        "waiting" to "tarrying",
        "send" to "dispatch",
        "sending" to "dispatching",
        "sent" to "didst dispatch",
        "build" to "erect",
        "building" to "erecting",
        "built" to "didst erect",
        "keep" to "safeguard",
        "die" to "perish",
        "dying" to "perishing",
        "died" to "didst perish",
        "sleeping" to "in slumber",
        "slept" to "didst slumber",
        "pray" to "beseech the Almighty",
        "praying" to "beseeching the heavens",
        "remember" to "recall to mind",
        "forget" to "allow to fade from memory",
        "choose" to "elect",
        "wish" to "desire most fervently",
        "hope" to "holdeth hope",
        "fear" to "dread most greatly",
        "crying" to "weeping",
        "cried" to "didst weep",
        "looking" to "gazing upon",
        "looked" to "didst gaze upon",
        "use" to "employ",
        "using" to "employing",
        "used" to "didst employ",
        "play" to "make merry",
        "playing" to "making merry",
        "turn" to "pivot",
        "put" to "place",
        "set" to "arrange",
        "watch" to "observe with great care",
        "become" to "transform into",
        "begin" to "commence",
        "seem" to "doth appear",
        "happen" to "come to pass",
        "lose" to "suffer loss of",
        "lost" to "didst lose",
        "allow" to "grant permission",
        "appear" to "manifest",
        "create" to "bring into being",
        "destroy" to "lay waste to",
        "share" to "distribute amongst",
        "steal" to "pilfer",
        "hide" to "conceal",
        "break" to "shatter",
        "fix" to "mend",
        "catch" to "seize mid-flight",
        "push" to "shove forth",
        "pull" to "draw toward",
        "climb" to "ascend",
        "fall" to "tumble",
        "jump" to "leap",
        "fly" to "soar through the heavens",
        "swim" to "traverse the waters",
        "burn" to "set aflame",

        // === COMMON ADJECTIVES ===
        "young" to "of tender years",
        "clean" to "pure and unsullied",
        "dirty" to "most filthy and besmirched",
        "safe" to "well guarded",
        "dangerous" to "most perilous",
        "kind" to "most benevolent",
        "mean" to "of wicked temperament",
        "funny" to "most mirthful",
        "serious" to "of grave countenance",
        "strange" to "passing strange",
        "wonderful" to "most wondrous",
        "terrible" to "most dreadful",
        "perfect" to "without flaw or blemish",
        "healthy" to "hale and hearty",
        "wise" to "most sagacious",
        "busy" to "occupied with many labours",
        "full" to "brimming over",
        "empty" to "barren and void",
        "easy" to "requiring little toil",
        "important" to "of utmost consequence",
        "different" to "of a differing nature",
        "long" to "of great length",
        "short" to "of modest stature",
        "high" to "most lofty",
        "low" to "of humble position",
        "right" to "righteous and true",
        "wrong" to "most erroneous",
        "true" to "verily so",
        "false" to "a vile falsehood",
        "possible" to "within the realm of possibility",
        "ready" to "prepared for battle",
        "sure" to "of absolute certainty",
        "clear" to "plain to behold",
        "nice" to "most agreeable",
        "warm" to "of pleasant warmth",
        "dry" to "parched as desert sand",
        "wet" to "soaked through",
        "soft" to "gentle as a maiden's touch",
        "rough" to "coarse and rugged",
        "sharp" to "keen-edged",
        "dull" to "blunt and witless",

        // === COMMON NOUNS ===
        "time" to "the passage of hours",
        "men" to "menfolk",
        "women" to "the womenfolk",
        "people" to "the common folk",
        "person" to "a soul",
        "world" to "all the known realm",
        "lord" to "my lord",
        "knight" to "a noble knight",
        "battle" to "a great clash of arms",
        "land" to "the domain",
        "castle" to "the fortress",
        "bird" to "a creature of the air",
        "tree" to "a great oak",
        "river" to "the flowing waters",
        "mountain" to "the great peak",
        "sea" to "the vast ocean",
        "sky" to "the heavens above",
        "hand" to "one's hand",
        "head" to "one's crown",
        "heart" to "one's beating heart",
        "blood" to "the crimson lifeblood",
        "death" to "the cold embrace of death",
        "life" to "one's mortal existence",
        "god" to "the Almighty",
        "child" to "a young whelp",
        "brother" to "mine own brother",
        "sister" to "mine own sister",
        "son" to "one's firstborn son",
        "daughter" to "one's fair daughter",
        "room" to "the chamber",
        "story" to "a tale",
        "name" to "one's given name",
        "place" to "a locale",
        "game" to "a contest of skill",
        "problem" to "a vexing matter",
        "question" to "an inquiry",
        "answer" to "a reply",
        "idea" to "a notion",
        "power" to "great might",
        "family" to "one's kin",
        "boy" to "a young lad",
        "thing" to "a matter",
        "stuff" to "sundry goods",
        "way" to "the path forward",
        "year" to "a year's turn",
        "month" to "a moon's cycle",
        "minute" to "a brief moment",
        "second" to "an instant",
        "hour" to "an hour's glass",
        "snow" to "winter's mantle",
        "wind" to "the gale",
        "earth" to "the mortal earth",
        "stone" to "the rock",
        "gold" to "gleaming gold",
        "silver" to "fine silver",
        "iron" to "wrought iron",
        "glass" to "crystal",
        "wood" to "timber",
        "wall" to "the rampart",
        "garden" to "the grounds",
        "field" to "the meadow",
        "forest" to "the woodland",
        "bridge" to "the crossing",
        "army" to "a host of warriors",
        "weapon" to "an instrument of war",
        "shield" to "one's buckler",
        "armor" to "plate and mail",
        "crown" to "the royal crown",
        "throne" to "the seat of power",
        "flag" to "the banner",
        "map" to "a chart of the realm",
        "sign" to "a portent",
        "law" to "the decree",
        "rule" to "the edict",
        "reason" to "sound judgement",
        "chance" to "fortune's whim",
        "dream" to "a vision",
        "secret" to "a guarded secret",
        "gift" to "an offering",
        "voice" to "one's voice",
        "pain" to "great suffering",
        "joy" to "great jubilation",
        "anger" to "wrath",

        // === COMMON ADVERBS & MISC ===
        "very" to "most",
        "really" to "verily",
        "just" to "merely",
        "only" to "solely",
        "still" to "yet still",
        "also" to "likewise",
        "here" to "hither",
        "there" to "thither",
        "now" to "at this present hour",
        "then" to "at that hour",
        "never" to "ne'er",
        "always" to "forevermore",
        "maybe" to "mayhaps",
        "perhaps" to "perchance",
        "together" to "as one",
        "away" to "hence",
        "back" to "henceforth returning",
        "nothing" to "naught",
        "everything" to "all that existeth",
        "something" to "a thing of import",
        "someone" to "a soul unknown",
        "everyone" to "all souls present",
        "nobody" to "not a single soul",
        "enough" to "a sufficient measure",
        "almost" to "very nearly",
        "again" to "once more",
        "often" to "oft",
        "soon" to "ere long",
        "already" to "already so",
        "finally" to "at long last",
        "probably" to "in all likelihood",
        "actually" to "in truth",
        "quickly" to "with great haste",
        "slowly" to "at a ponderous pace",
        "early" to "at first light",
        "late" to "at a tardy hour",
        "usually" to "as is customary",
        "sometimes" to "upon occasion",

        // === COMMON PHRASES ===
        "i dont know" to "I know not",
        "i don't know" to "I know not",
        "idk" to "I confess ignorance in this matter",
        "i think" to "methinks",
        "i feel like" to "mine heart doth tell me",
        "for real" to "upon mine honour, 'tis true",
        "i mean" to "what I doth intend to say",
        "you know" to "as thou art well aware",
        "right now" to "at this very moment",
        "of course" to "but of course",
        "come on" to "make haste",
        "shut up" to "hold thy tongue",
        "go away" to "begone from my sight",
        "i cant" to "I am unable",
        "not yet" to "the time hath not yet come",
        "lets go" to "let us venture forth",
        "let's go" to "let us venture forth",
        "whats up" to "what news dost thou bring",
        "what's up" to "what news dost thou bring",
        "by the way" to "I would also note",
        "in my opinion" to "in mine humble estimation",
        "to be honest" to "in all honesty before God",
        "i promise" to "upon mine sacred honour"
    )

    val emojiMap: HashMap<String, String> = hashMapOf(
        "😂" to "[doth cackle most heartily]",
        "💀" to "[slain where I stood]",
        "🔥" to "[a most fearsome blaze]",
        "❤️" to "[mine heart doth flutter]",
        "❤" to "[mine heart doth flutter]",
        "😭" to "[weeping like a widow at the gates]",
        "🙄" to "[rolls mine eyes toward the heavens]",
        "😤" to "[snorting with the fury of a warhorse]",
        "🤣" to "[rolling in the mud with laughter]",
        "😩" to "[collapsing upon the cold stone floor]",
        "🥺" to "[gazing up with the eyes of a wounded squire]",
        "😏" to "[smiling with the cunning of a court jester]",
        "🤡" to "[the fool of the royal court]",
        "😈" to "[wearing the face of a most mischievous imp]",
        "👀" to "[watching from behind mine visor]",
        "💅" to "[polishing mine gauntlets with great satisfaction]",
        "🤦" to "[burying mine face in mine hands]",
        "🫡" to "[bowing most dutifully, milord]",
        "🫠" to "[melting like candle wax before the throne]",
        "🧢" to "[a cap of falsehood upon thine head]",
        "💯" to "[one hundred farthings of pure truth]",
        "😊" to "[beaming with the warmth of a hearth fire]",
        "😍" to "[mine eyes doth turn to hearts]",
        "🥰" to "[surrounded by the warmth of adoration]",
        "😡" to "[face burning with the wrath of a thousand suns]",
        "😱" to "[struck with terror most profound]",
        "🤔" to "[stroking mine beard in deep contemplation]",
        "👑" to "[a crown most deserved]",
        "⚔️" to "[blades crossed in honour]",
        "🛡️" to "[shielded from thine attack]",
        "🏰" to "[within the castle walls]",
        "💪" to "[flexing with the might of a siege engine]",
        "🙏" to "[hands clasped in fervent prayer]",
        "👋" to "[waving from the castle rampart]",
        "✨" to "[sparkling with enchantment]",
        "🎉" to "[a grand celebration most joyous]",
        "💔" to "[mine heart cloven in twain]",
        "😴" to "[slumbering like a bear in winter]",
        "🤮" to "[retching most violently]",
        "🫣" to "[peeking through mine fingers]",
        "😮‍💨" to "[exhaling with great exhaustion]"
    )

    val rageCries = listOf(
        "FOR THE REALM!",
        "DEATH BEFORE DISHONOUR!",
        "HAVE AT THEE, KNAVE!",
        "BY MINE SWORD I SHALT SMITE THEE!",
        "THE RAVENS SHALL FEAST THIS NIGHT!",
        "TO ARMS, TO ARMS!",
        "NONE SHALL PASS!",
        "I SHALL CLEAVE THEE IN TWAIN!",
        "BY THE BLOOD OF KINGS!",
        "STEEL THY NERVES AND CHARGE!"
    )

    // Period-specific overrides for Tudor mode
    val tudorOverrides: HashMap<String, String> = hashMapOf(
    )

    // Period-specific overrides for Pirate mode
    val pirateOverrides: HashMap<String, String> = hashMapOf(
        "drink" to "grog",
    )

    fun translate(word: String): String? {
        return map[word.lowercase().trim()]
    }

    fun translateEmoji(text: String): String? {
        return emojiMap[text]
    }

    fun translateWithPeriod(word: String, period: Int): String? {
        val key = word.lowercase().trim()
        return when (period) {
            1 -> tudorOverrides[key] ?: map[key]
            2 -> pirateOverrides[key] ?: map[key]
            else -> map[key]
        }
    }

    fun translatePhrase(text: String): String? {
        val lower = text.lowercase().trim()
        return map[lower]
    }

    fun getSuggestions(word: String): List<String> {
        val translated = map[word.lowercase().trim()] ?: return emptyList()
        return listOf(translated)
    }
}
