package com.medieval.keyboard

object MedievalFallbackMap {

    val map: HashMap<String, String> = hashMapOf(
        // Common substitutions
        "yes" to "aye",
        "yeah" to "aye, verily",
        "yep" to "aye",
        "no" to "nay",
        "nope" to "nay, I shalt not",
        "you" to "thou",
        "your" to "thy",
        "yours" to "thine",
        "hello" to "hail",
        "hi" to "well met",
        "hey" to "hark",
        "goodbye" to "fare thee well",
        "bye" to "Godspeed",
        "please" to "prithee",
        "sorry" to "I cry thee mercy",
        "thanks" to "thou hast my gratitude",
        "friend" to "comrade",
        "enemy" to "knave",
        "stupid" to "addlepated",
        "ugly" to "misbegotten",
        "drunk" to "in one's cups",
        "crazy" to "moon-mad",
        "money" to "coin",
        "food" to "victuals",
        "eat" to "sup",
        "walk" to "venture forth",
        "run" to "make great haste",
        "house" to "dwelling",
        "home" to "hearth and dwelling",
        "clothes" to "garments",
        "phone" to "enchanted scrying glass",
        "internet" to "the great arcane network",
        "car" to "iron carriage",
        "computer" to "thinking engine",
        "police" to "the constabulary",
        "doctor" to "apothecary",
        "work" to "toil",
        "job" to "toil",
        "boss" to "liege",
        "cool" to "most gallant",
        "bad" to "most foul",
        "awesome" to "most magnificent",
        "annoying" to "vexing",
        "fight" to "skirmish",
        "kill" to "smite",
        "love" to "adore",
        "hate" to "despise",
        "good" to "most worthy",
        "great" to "most splendid",

        // Slang — original
        "lol" to "I doth laugh heartily",
        "omg" to "by all the saints",
        "wtf" to "what devilry is this",
        "ok" to "aye, so be it",
        "okay" to "aye, so be it",
        "bro" to "good fellow and brother in arms",
        "dude" to "good sir",
        "girl" to "maiden",
        "guy" to "fellow",
        "sick" to "most gallant",
        "fire" to "of great magnificence",
        "lit" to "most resplendent",
        "bruh" to "good fellow",
        "fam" to "mine blood and kin",
        "goat" to "the greatest champion this kingdom hath ever witnessed",
        "shade" to "veiled insult most cunning",
        "tea" to "gossip most tantalizing",

        // Greetings & casual chat slang
        "wassup" to "hark, what tidings dost thou bring?",
        "wazzup" to "hark, what tidings dost thou bring?",
        "sup" to "hark, what tidings dost thou bring?",
        "wyd" to "what manner of toil dost thou undertake at this hour?",
        "hmu" to "send a raven unto me",
        "brb" to "I shall return hence, tarry a moment",
        "gtg" to "I must away with great haste",
        "ttyl" to "we shall speak anon",
        "ngl" to "I shall not deceive thee",
        "tbh" to "in honest truth, I confess",
        "imo" to "methinks",
        "imho" to "in my most humble opinion, good sir",
        "smh" to "I shaketh mine head in great despair",
        "lmao" to "I am deceased with laughter, forsooth",
        "rofl" to "I doth roll upon the ground in great hysterics",
        "gg" to "well fought, thou gallant warrior",
        "wp" to "most valiant effort, good knight",

        // Gen Z slang — updated & expanded
        "cap" to "thou speakest falsehoods, knave",
        "slay" to "thou dost smite all before thee",
        "ate" to "thou didst feast upon that challenge most gloriously",
        "periodt" to "and so it is decreed, henceforth",
        "bussin" to "forsooth, 'tis a most glorious feast",
        "mid" to "most mediocre, hardly worth a farthing",
        "based" to "of most noble conviction",
        "cringe" to "most embarrassing, I cry thee mercy",
        "ratio" to "thou hast been bested in the court of public opinion",
        "bet" to "upon my honour, so be it",
        "deadass" to "in utmost sincerity, I swear upon mine soul",
        "facts" to "thou speakest true, verily",
        "lowkey" to "in secret, lest the king's men hear",
        "highkey" to "I shout it from the highest rampart",
        "vibe" to "the humour of the moment",
        "vibing" to "dwelling in most pleasant humour",
        "sus" to "most suspicious, I dare say",
        "extra" to "most theatrical beyond all reason",
        "basic" to "plain as a peasant's gruel",
        "woke" to "most enlightened beyond thine station",
        "clout" to "renown and standing in the kingdom",
        "shook" to "rattled to mine very bones",

        // Hype & reaction slang
        "savage" to "most ruthless and without mercy",
        "salty" to "most bitter, like the sea itself",
        "flex" to "a most ostentatious display of one's riches",
        "drip" to "most resplendent raiment",
        "fit" to "a most fine set of garments",
        "slaps" to "doth strike mine ears most pleasurably",
        "banger" to "a most rousing ballad for the ages",
        "dead" to "I am slain by this jestry",

        // Dating & social slang
        "ghost" to "vanish like a specter",
        "ghosted" to "vanished like a wraith in the night without word",
        "situationship" to "a courtship of most uncertain honour",
        "rizz" to "the art of courtly charm",
        "simp" to "a lovesick fool pining most pitifully",
        "stan" to "a most devoted admirer, bordering on madness",
        "ship" to "I dost pray these two souls be betrothed",
        "otp" to "my most fervently wished betrothal",
        "fomo" to "the fear of missing the great feast",
        "yolo" to "thou only walketh this earth once, seize the day",

        // Persona slang
        "sigma" to "a lone wolf of most noble bearing",
        "alpha" to "the chief lord of the pack",
        "beta" to "a most craven follower",
        "npc" to "a mere peasant of no consequence",

        // Multi-word phrases
        "fr fr" to "verily, upon my honour, 'tis so",
        "no cap" to "I speak no falsehood, upon my troth",
        "no way" to "by God's wounds, thou jest surely",
        "say less" to "speak no further, I heed thee",
        "no rizz" to "possessing not a shred of courtly grace",
        "rent free" to "haunting thy thoughts like a restless wraith",
        "main character" to "the hero of thine own great tale",
        "glow up" to "a most wondrous transformation, like a phoenix reborn",
        "caught in 4k" to "caught in the act by the royal scribe",
        "touch grass" to "venture thou forth into the fields, thou pale hermit",
        "i'm weak" to "thou hast robbed me of all strength through laughter",
        "lowkey crying" to "mine eyes doth leak most quietly",
        "it's giving" to "it doth exude the essence of",
        "that's wild" to "most extraordinary, by the saints",
        "this ain't it" to "nay, this is most foul and unworthy",
        "it's not giving" to "it doth fail to exude any worthy essence",
        "hits different" to "doth strike the soul in a manner most peculiar",
        "hit different at 3am" to "doth weigh upon the soul most heavily in the dead of night",
        "understood the assignment" to "thou hast heeded the quest most gallantly",
        "periodt no cap" to "so it is written, so it shall be done",
        "we don't do that here" to "such conduct is most unwelcome in this kingdom",
        "ate and left no crumbs" to "feasted gloriously and left naught for the ravens",
        "understood" to "thy words hath reached mine ears, so be it",
        "L" to "a most grievous defeat, thou wretch",
        "W" to "a most glorious victory, well met",

        // More common words
        "man" to "fellow",
        "woman" to "lady",
        "wife" to "beloved wife",
        "husband" to "lord husband",
        "king" to "sovereign",
        "queen" to "sovereign lady",
        "city" to "great city",
        "town" to "hamlet",
        "village" to "hamlet",
        "water" to "water",
        "beer" to "ale",
        "wine" to "mead",
        "sword" to "blade",
        "horse" to "steed",
        "dog" to "hound",
        "cat" to "mouser",
        "night" to "eve",
        "day" to "morrow",
        "morning" to "morrow's dawn",
        "evening" to "vespers",
        "week" to "sennight",
        "today" to "this very day",
        "tomorrow" to "on the morrow",
        "yesterday" to "yester-eve",
        "want" to "desire",
        "need" to "require most urgently",
        "have" to "possess",
        "go" to "venture forth",
        "come" to "approach",
        "see" to "behold",
        "look" to "gaze upon",
        "think" to "methinks",
        "know" to "doth know",
        "say" to "proclaim",
        "tell" to "declare",
        "give" to "bestow",
        "take" to "seize",
        "make" to "forge",
        "get" to "procure",
        "try" to "endeavor",
        "help" to "lend thine aid",
        "stop" to "halt",
        "wait" to "tarry",
        "fast" to "swift",
        "slow" to "leisurely",
        "big" to "great",
        "small" to "wee",
        "old" to "ancient",
        "new" to "freshly wrought",
        "happy" to "merry",
        "sad" to "woeful",
        "angry" to "wrathful",
        "scared" to "afeared",
        "tired" to "weary",
        "hungry" to "famished",
        "rich" to "wealthy",
        "poor" to "destitute",
        "strong" to "stalwart",
        "weak" to "feeble",
        "smart" to "learned",
        "brave" to "valiant",
        "afraid" to "craven",
        "alive" to "among the living",
        "war" to "great conflict",
        "peace" to "tranquility",
        "truth" to "verity",
        "lie" to "falsehood",
        "God" to "the Almighty",
        "devil" to "the fiend",
        "church" to "the chapel",
        "school" to "academy of learning",
        "book" to "tome",
        "letter" to "missive",
        "message" to "dispatch",
        "text" to "scroll",
        "email" to "enchanted missive",
        "password" to "secret incantation",
        "wifi" to "ethereal connection",
        "battery" to "arcane reserves",
        "selfie" to "self-portrait most vain",
        "photo" to "portrait",
        "video" to "moving portrait",
        "movie" to "grand theatrical spectacle",
        "music" to "minstrel's art",
        "song" to "ballad",
        "dance" to "revelry",
        "party" to "grand feast",
        "date" to "courtship",
        "relationship" to "courtship most serious",
        "breakup" to "severing of bonds",
        "boring" to "tedious",
        "exciting" to "thrilling",
        "beautiful" to "most fair",
        "handsome" to "comely",
        "thank" to "give thanks",
        "children" to "younglings",
        "baby" to "babe",
        "sleep" to "slumber",
        "wake" to "rouse",
        "laugh" to "cackle with mirth",
        "cry" to "weep",
        "smile" to "grin most warmly",
        "yell" to "bellow",
        "whisper" to "murmur",
        "speak" to "utter",
        "quiet" to "hush",
        "loud" to "thunderous",
        "dark" to "shrouded in shadow",
        "light" to "illuminated",
        "hot" to "scorching",
        "cold" to "possessing an air of effortless magnificence",
        "rain" to "heavens weep",
        "sun" to "celestial orb",
        "moon" to "pale moon",
        "star" to "heavenly body",
        "road" to "path",
        "street" to "thoroughfare",
        "door" to "portal",
        "window" to "casement",
        "bed" to "bedchamber",
        "table" to "board",
        "chair" to "seat",
        "store" to "merchant's shop",
        "buy" to "purchase",
        "sell" to "peddle",
        "pay" to "render payment",
        "free" to "without cost",
        "expensive" to "most costly",
        "cheap" to "of little worth",

        // Street & friend slang
        "huzz" to "thou most disreputable wench of questionable virtue",
        "huz" to "thou most disreputable wench of questionable virtue",
        "bruzz" to "mine most trusted brother in arms",
        "bruz" to "mine most trusted brother in arms",
        "cuzz" to "mine kinsman of the realm",
        "cuz" to "mine kinsman of the realm",
        "gang" to "mine most loyal band of knights",
        "homie" to "mine sworn companion of the parish",
        "dawg" to "thou faithful hound, mine dearest ally",
        "sis" to "good maiden and sister of mine heart",
        "bestie" to "mine most cherished companion in this mortal realm",
        "twin" to "mine soul's mirror, we art one",
        "plug" to "mine most clandestine merchant of wares",
        "opps" to "mine sworn enemies and rival clan",
        "ops" to "mine sworn enemies and rival clan",
        "opp" to "a foe most treacherous from a rival house",
        "beef" to "a most bitter quarrel and blood feud",
        "fake" to "a most duplicitous and two-faced wretch",
        "snake" to "a viper most treacherous hiding in friendly garb",
        "rat" to "an informant most vile, a spy for the crown",
        "snitch" to "one who doth whisper secrets unto the king's men",
        "real" to "of the truest and most genuine nature",
        "unreal" to "so magnificent it straineth belief",
        "surreal" to "as strange as a dream sent by the faeries",

        // Street & friend multi-word phrases
        "ride or die" to "sworn to stand by mine side til the final battle",
        "day one" to "loyal since the very first cockcrow",
        "squash the beef" to "let us broker peace and end this blood feud",
        "on sight" to "I shall smite thee the moment thine wretched face appears",
        "move different" to "thou dost carry thyself unlike common peasantry",
        "built different" to "forged of sterner stuff than ordinary men",
        "no printer" to "mine word is mine bond, no royal decree needed",
        "real one" to "a soul of most genuine and noble character",
        "clout chaser" to "a glory hound seeking unearned renown",
        "pick me" to "one who doth grovel most pitifully for approval",

        // Hype & reaction slang
        "cooked" to "in most dire straits with no escape",
        "pressed" to "most vexed and wound up like a siege engine",
        "ick" to "a most revolting sensation hath overcome me",
        "obsessed" to "bewitched and consumed most entirely",
        "delulu" to "lost in delusions most fantastical and unfounded",
        "era" to "mine current chapter of this great tale",
        "fresh" to "most pristine and splendid in appearance",
        "hard" to "of the most uncompromising and impressive quality",
        "goated" to "elevated to legendary status beyond all others",
        "overrated" to "praised far beyond its meagre deserving",
        "underrated" to "deserving far greater renown than granted",
        "sleeper" to "a hidden gem known only to the most discerning",
        "trash" to "absolute refuse not worth a single farthing",
        "cope" to "find thyself some manner of comfort in defeat",
        "seethe" to "boil with rage most impotent and unbecoming",
        "mald" to "lose both thy composure and thy hair simultaneously",
        "swear" to "I doth swear upon mine honour",
        "lying" to "thou speakest nothing but falsehoods, thou deceiver",
        "relax" to "ease thy troubled mind, good sir",
        "chill" to "be of calm and pleasant humour",
        "hits" to "doth strike the palate most pleasurably",

        // Hype & reaction multi-word phrases
        "go crazy" to "descend into most glorious madness",
        "go off" to "unleash thy fury, hold nothing back",
        "go off sis" to "speak thy truth maiden, let the whole kingdom hear",
        "not me" to "prithee do not look upon me for such folly",
        "the way i" to "forsooth, observe how I doth",
        "i can't" to "mine strength doth fail me entirely",
        "i'm dead" to "thou hast slain me where I stood",
        "send help" to "dispatch thy swiftest raven, I am in dire peril",
        "it's over" to "the battle is lost, all hope hath fled",
        "we're so back" to "the army doth rise again, victory is nigh",
        "he's cooked" to "that poor wretch is well and truly done for",
        "bro is cooked" to "yonder fool hath sealed his own fate",
        "stick a fork in me" to "I am as done as a feast day pig upon the spit",
        "not the" to "by the saints, not this wretched",
        "the audacity" to "the sheer brazen impudence of this knave",
        "mad pressed" to "consumed by fury most unbecoming of thy station",
        "calm down" to "still thy tempestuous spirit, I prithee",
        "no chill" to "possessing not a single moment of peaceful temper",
        "got the ick" to "mine heart hath recoiled in disgust most profound",
        "caught feelings" to "mine heart hath been most inconveniently ensnared",
        "down bad" to "reduced to the most pitiful and lovesick state",
        "down horrendous" to "in a state of wretchedness beyond all description",
        "parasocial" to "devoted to one who knoweth not of thine existence",
        "delulu is the solulu" to "only through magnificent delusion doth one prevail",
        "touch starved" to "denied human warmth like a hermit in a cold tower",
        "in my villain era" to "I hath embraced mine darker nature most gleefully",
        "in my flop era" to "currently dwelling in a most unproductive chapter",
        "in my healing era" to "mending mine wounds like a knight after great battle",
        "in my glow up era" to "transforming like a dragon shedding its old scales",
        "roman empire" to "that which occupies mine thoughts unbidden and often",
        "he doesn't know" to "the poor fool remaineth blissfully unaware",
        "understood the vibe" to "hath read the room with most admirable perception",
        "didn't pass the vibe check" to "hath failed the test of pleasant humour most miserably",

        // Argument & clap back slang
        "you're cooked" to "thou art finished, prepare thy affairs",
        "ratio'd" to "bested in the court of public opinion, thou wretched fool",
        "i said what i said" to "mine words stand firm as castle walls",
        "keep my name out your mouth" to "speak not mine name with thy wretched tongue",
        "say that to my face" to "speak those words whilst facing mine blade, coward",
        "on god" to "I swear upon all that is holy and sacred",
        "not lying" to "every word from mine lips is pure truth",
        "nah bro" to "nay good sir, I shalt not accept this",
        "bro really said" to "the audacity of this knave who proclaimed",
        "bro thought" to "this fool genuinely believed in his addled mind",
        "tell me why" to "prithee explain to me the reasoning behind this madness",
        "for what" to "for what earthly reason, I demand to know",
        "at what cost" to "but at what terrible price was this victory won",
        "this you?" to "art thou truly responsible for this shameful act?",
        "caught lacking" to "discovered in a most vulnerable and unguarded state",
        "stay mad" to "wallow in thy bitterness, it matters not to me",
        "cry about it" to "weep thy tears into the river, I care not",
        "touch some grass" to "remove thyself from thy stone tower and breathe fresh air",
        "log off" to "close thy enchanted scrying glass and venture outside",
        "get a life" to "acquire purpose beyond this screen, thou hollow vessel",
        "get good" to "hone thy skills or be forever bested, thou novice",
        "skill issue" to "a deficiency of ability most fundamental",
        "cope and seethe" to "wallow in denial and simmer in thine own fury",
        "touch grass and mald" to "venture outside and rage at the very sky",

        // Food & daily life slang phrases
        "no cap bussin" to "upon my honour this feast is of divine quality",
        "it's giving slay" to "it doth radiate excellence most magnificent",
        "slaps hard" to "assaults mine senses with magnificent force",
        "fire ngl" to "most magnificent, I shall not deceive thee",
        "mid af" to "most thoroughly mediocre in every conceivable way",
        "certified banger" to "decreed by royal proclamation to be a masterwork",
        "goated with the sauce" to "a legend draped in the most mysterious and potent gifts",
        "the sauce" to "the mysterious secret ingredient of greatness",
        "dripped out" to "adorned in the most magnificent raiment imaginable",
        "clean fit" to "garments of the most impeccable and noble quality"
    )

    fun translate(word: String): String? {
        return map[word.lowercase().trim()]
    }

    fun translatePhrase(text: String): String? {
        val lower = text.lowercase().trim()
        return map[lower]
    }

    fun getSuggestions(word: String): List<String> {
        val translated = map[word.lowercase().trim()] ?: return emptyList()
        return listOf(translated)
    }
}
